# OpenTelemetry Collector Configuration for LGTM Stack
# This collector receives OTLP data from applications and exports to Loki, Grafana, Tempo, and Prometheus

receivers:
  # OTLP receiver for traces, metrics, and logs
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  # Prometheus receiver to scrape metrics from applications
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-lgtm-app"
          scrape_interval: 15s
          static_configs:
            - targets: ["app:8080"] # Your Go app container
          metrics_path: "/metrics"

processors:
  # Batch processor for better performance
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Resource processor to add/modify resource attributes
  resource:
    attributes:
      - key: deployment.environment
        value: "demo"
        action: upsert
      - key: service.namespace
        value: "otel-lgtm"
        action: upsert

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512
    check_interval: 4s

exporters:
  # Export traces to Tempo
  otlp/tempo:
    endpoint: http://tempo:3200
    tls:
      insecure: true

  # Export metrics to Prometheus via remote write
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true

  # Export logs to Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

  # Debug exporter for troubleshooting
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo, logging]

    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite, logging]

    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, logging]

  extensions: []

  telemetry:
    logs:
      level: "info"
    metrics:
      level: basic
      address: 0.0.0.0:8888
